/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package librerias;

import java.io.File;
import java.io.IOException;

import com.fasterxml.jackson.databind.ObjectMapper;



public class Library {
    
	public static void main(String[] args) throws IOException {
		Participante participante = new Participante("RM", "Real Madrid");

		ObjectMapper mapper = new ObjectMapper();
		String participanteSerializado = mapper.writeValueAsString(participante);




		mapper.writeValue(new File("participante.json"), participante);
		System.out.println(participanteSerializado);
		Participante participante2;// = deserializar(participanteSerializado);
		// System.out.println(participante2.getId() + " - " + participante2.getNombre());
		participante2 = mapper.readValue(participanteSerializado, Participante.class);
		System.out.println();
		}

	public boolean someLibraryMethod() {
		// TODO Auto-generated method stub
		return false;
	} 
	
	
	
}
